### ISSUE TITLE
I can't download sonica from the link in the e-mail.

### ISSUE THREAD

**Issue by zr4in** [sonica-nbiot/sonica#2]
The e-mail said

> We are happy to inform you that your request for acquiring SONICA has been approved. You can download it from http://metro.cs.ucla.edu/login.html

but after logging in, it was redirected to http://metro.cs.ucla.edu/codeshare/data_home.php, which is an empty page.
Any help would be greatly appreciated.

**Comment by Yaoshicn** [comment]
Same here.

**Comment by haroldfeng** [comment]
Did you successfully set up the environment? I use the latest code and run it, but the device doesn't attach.

**Comment by zr4in** [comment]
> Did you successfully set up the environment? I use the latest code and run it, but the device doesn't attach.

Sorry that I cannot recall it clearly. I think you can contact with the authors for more instructions. I am closing this issue.
