### ISSUE TITLE
Every ISMI Is 901700000040740

### ISSUE THREAD

**Issue by 0x657373656C6C** [sonica-nbiot/sonica#4]
Hello,

No matter what I try, every IMSI is: 901700000040740

I grepped the entire codebase and that number is not present anywhere. 

EPC Logs:

Attach request 238 -- IMSI: 901700000040740
NB Attach request -- eNB-UE S1AP Id: 3
NB Attach request -- Attach type: 2
NB Attach Request -- UE Network Capabilities EEA: 11110000
NB Attach Request -- UE Network Capabilities EIA: 01110000
NB Attach Request -- UE Network Capabilities s1u_data=0, upciot=0, cpciot=1.
Attach Request -- MS Network Capabilities Present: true
PDN Connectivity Request -- EPS Bearer Identity requested: 0
PDN Connectivity Request -- Procedure Transaction Id: 1
PDN Connectivity Request -- ESM Information Transfer requested: true
NB Attach Request -- handle_imsi_attach_request_unknown_ue.
User not found at HSS. IMSI: 901700000040740
User not found. IMSI 901700000040740

Let me know if I can help further.

**Comment by MikeEmbedded** [comment]
Hi @joelsernamoreno.

Sorry for late answer. I was in vacation.

Thank you very much for information about SIM cards. It was a question for me also.

I need to move my system from Respberry Pi4B to a PC at the moment.

I will let yoy know.
